# Generated by Django 4.2.14 on 2025-10-27 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_book_cover_image_book_is_active_book_pages_and_more'),
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('total_customers', models.PositiveIntegerField(default=0, verbose_name='Общее количество клиентов')),
                ('new_customers', models.PositiveIntegerField(default=0, verbose_name='Новые клиенты')),
                ('returning_customers', models.PositiveIntegerField(default=0, verbose_name='Постоянные клиенты')),
                ('average_customer_value', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Средняя стоимость клиента')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Статистика клиентов',
                'verbose_name_plural': 'Статистика клиентов',
                'ordering': ['-date'],
                'unique_together': {('date',)},
            },
        ),
        migrations.CreateModel(
            name='SalesStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Дата')),
                ('total_orders', models.PositiveIntegerField(default=0, verbose_name='Количество заказов')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Общая выручка')),
                ('total_books_sold', models.PositiveIntegerField(default=0, verbose_name='Количество проданных книг')),
                ('average_order_value', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Средний чек')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Статистика продаж',
                'verbose_name_plural': 'Статистика продаж',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='TopSellingBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('quantity_sold', models.PositiveIntegerField(verbose_name='Количество проданных')),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Выручка')),
                ('rank', models.PositiveIntegerField(verbose_name='Позиция в рейтинге')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.book', verbose_name='Книга')),
            ],
            options={
                'verbose_name': 'Топ продаваемых книг',
                'verbose_name_plural': 'Топ продаваемых книг',
                'ordering': ['-date', 'rank'],
                'unique_together': {('date', 'book')},
            },
        ),
        migrations.RemoveField(
            model_name='pageview',
            name='user',
        ),
        migrations.RemoveField(
            model_name='purchaseevent',
            name='order',
        ),
        migrations.RemoveField(
            model_name='purchaseevent',
            name='user',
        ),
        migrations.RemoveField(
            model_name='searchquery',
            name='user',
        ),
        migrations.DeleteModel(
            name='BookView',
        ),
        migrations.DeleteModel(
            name='PageView',
        ),
        migrations.DeleteModel(
            name='PurchaseEvent',
        ),
        migrations.DeleteModel(
            name='SearchQuery',
        ),
    ]
