# Generated by Django 4.2.14 on 2025-10-27 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_avatar_profile_city_profile_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('guest', 'Гость'), ('buyer', 'Покупатель'), ('manager', 'Менеджер'), ('admin', 'Администратор')], default='buyer', max_length=20, verbose_name='Роль на сайте'),
        ),
    ]
