# Generated by Django 4.2.14 on 2025-10-27 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='blocked_reason',
            field=models.TextField(blank=True, verbose_name='Причина блокировки'),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_blocked',
            field=models.BooleanField(default=False, verbose_name='Заблокирован'),
        ),
    ]
