# Generated by Django 4.2.14 on 2025-11-10 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_auto_20251028_0032"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="description",
            field=models.TextField(
                blank=True, help_text="Детальное описание действия пользователя"
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("created", "Создано"),
                    ("updated", "Обновлено"),
                    ("deleted", "Удалено"),
                    ("viewed", "Просмотрено"),
                    ("login", "Вход в систему"),
                    ("logout", "Выход из системы"),
                    ("registered", "Регистрация"),
                    ("backup_created", "Создана резервная копия"),
                    ("backup_restored", "Восстановлена резервная копия"),
                    ("backup_deleted", "Удалена резервная копия"),
                ],
                max_length=100,
            ),
        ),
    ]
